layout_spectrum: 0.9638905
typography_spectrum: 0.7423195
color:
  saturation: 0.1734907
  lightness: 0.08983377
  brandStrength: 0.2515536
  rhythmicContrast: 0.3713427
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: All-Colors
